### ISSUE TITLE
Missing argument for since-commit

### ISSUE THREAD

**Issue by Huskydog9988** [trufflesecurity/trufflehog#1002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

v3.23.1

### Trace Output

https://gist.github.com/Huskydog9988/af7f1aeaf7d8cf7639ee426be7203b50

### Expected Behavior

Should provided the necessary commit for the `--since-commit` arg.

### Actual Behavior

No commit was provided

### Steps to Reproduce

Use the github action on v3.23.1

## Environment
Github actions

### References

Haven't found another case yet.

**Comment by clarkedb** [comment]
It looks like #996 made it so that the `base` input for the action is no longer required and falls back to `''` which means that if `base` is not specified in a workflow file, the command ends up getting the flag `--since-commit ""` which leads to a `trufflehog` error of

```text
trufflehog: error: expected argument for flag '--since-commit'
```

The default probably should not be `''` since that will never work making `base` effectively `required` even though it is technically not required an has a default.

Then #999 made it worse by updating the action yaml to pass in `${{ inputs.base.default }}` instead of `${{ inputs.base}}` to the `--since-commit` flag. This means that `trufflehog` will **always** get `--since-commit ""` even if the user's workflow does specify `base`. So now `''` isn't the default, it's the only value ever used. The way that `defaults` work is that if no value is provided for an input, then referencing `input.INPUT_NAME` will grab the value. There is no need to explicitly grab the `default` for the input.

To get this working again, #999 should be reverted so that the actual value of `base` gets used. I've submitted #1004 in order to resolve that. Ultimately #996 should be reevaluated as well since the default value `''` will never be useful.

In the mean time, if you update your GitHub Action workflow to specify an earlier version, you should be able to get by until this is resolved and released.

**Comment by Huskydog9988** [comment]
As per your suggestion I moved the action to `v3.23.0`, and seem to have found another issue. I'm not sure if this is a seperate issue due to it also revolving around the since-commit arg. While this is pure speculation of my part, I can only assume that the true cause spans further back then #999.
https://gist.github.com/Huskydog9988/511f1ff46216455b75dbd02158d6339b

**Comment by muratzh** [comment]
after I moved to 3.23.0 it's scanning but not showing findings. Does anyone know why?
