### ISSUE TITLE
trufflehog: error: unknown long flag '--regex'

### ISSUE THREAD

**Issue by mohanss08** [trufflesecurity/trufflehog#1303]
Hello Team,

I have downloaded `trufflehog_3.33.0_linux_amd64.tar.gz` and extracted on my Ubuntu server. So when i run the scan (Command given below) it always fails.

```
cd /opt/trufflehog
./trufflehog --regex --entropy=False --max_depth=3 git ssh://user@gerrit.review.com:29418/Android/linux-lite --only-verified
trufflehog: error: unknown long flag '--regex', try --help
```
Even below doesn't work.

```
./trufflehog git --regex --entropy=False --max-depth=3 ssh://user@gerrit.review.com:29418/Android/linux-lite
trufflehog: error: unexpected ssh://user@gerrit.review.com:29418/Android/linux-lite, try --help
````
Please let me know whats wrong with my command?

**Comment by Recurzion** [comment]
Hi @mohanss08, it seems like both of your commands have syntax errors. I haven't dug in too deep, but it looks like your first command needs to pass "git <url>" as the first argument instead of putting the git URL in the middle of the arguments.

Your second command has "--entropy=False" which is not correct. It should just be --entropy.
