### ISSUE TITLE
Regex Only Matching One Item

### ISSUE THREAD

**Issue by clay584** [trufflesecurity/trufflehog#138]
When creating my own regex rules, its only matching the last of these lines which are in my test file. This is a Cisco router device configuration. It should match them all (validated in Sublime Text 3's regex search).

Pattern file:
```
{
    "Cisco Password": "\\$\\d+\\$.*"
}
```

Sample Text:
```
username johndoe1 privilege 15 secret 5 $1$2pGo$3MMUjCeoCGO4QQ5PBV6aF.
username johndoe2 privilege 15 secret 5 $1$3pfF$ukdNDHRM0bv2QpeOriuyw/
username johndoe3 privilege 15 secret 5 $1$1866$qBd2LCZ4Rf36JLeR3gzw91
username johndoe4 privilege 15 secret 5 $1$bmdJ$sX2EpU.uCCvnu8ljVT27k.
username johndoe5 privilege 15 secret 5 $1$MlnJ$VyYAg2gxOfHpAflbbea5B.
```

**Comment by nickwinn** [comment]
👍 Bump, experiencing the same issue. 

Also can someone drop a sample of email address matching regex? I can't get my regex to work properly.

Thank You

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

This is probably fixed in the new release.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
