### ISSUE TITLE
Getting "error occurred while collecting chunks" with latest trufflehog version

### ISSUE THREAD

**Issue by shivaprasad-balaji** [trufflesecurity/trufflehog#1447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

Running the latest trufflehog version in github action.

### Trace Output

https://gist.github.com/shivaprasad-balaji/40063e8dc7b28f4390cfacffc33bf0cb

### Expected Behavior

Trufflehog should scan the code for issues and pass if nothing is found

### Actual Behavior

Trufflehog is failing with the error 
error	trufflehog	error occurred while collecting chunks	{"error": "could not scan repo: unable to resolve base ref: object not found"}

### Steps to Reproduce

1. Use latest trufflehog@main in github action 
2. Perform scan on code  
This happens on every scan

## Environment
 Ubuntu
  22.04.2
  LTS

* #0000

**Comment by zricethezav** [comment]
@shivaprasad-balaji thanks for opening the issue. Couple questions:
1. It sounds like this bug is for the trufflehog github action. How are you running it? Against PRs? Pushes? Providing the workflow you're using would be helpful
2. Does this happen for every github event (push, opening a PR, etc)? 
3. Are you running this scan on forked code?

Any additional details would be helpful.
