### ISSUE TITLE
`panic: runtime error: index out of range [2] with length 2` when using `--include-members`

### ISSUE THREAD

**Issue by selfagency** [trufflesecurity/trufflehog#1539]
### TruffleHog Version
`dev` -- because i manually compiled on windows

### Trace Output

https://gist.github.com/selfagency/1b25d4da9c86e8803d8bbd860a976a46

### Expected Behavior

For the command to have succeeded

### Actual Behavior

```
panic: runtime error: index out of range [2] with length 2

goroutine 130 [running]:
github.com/trufflesecurity/trufflehog/v3/pkg/sources/github.(*Source).scanComments(0xc0001a6c00, {0x2789600?, 0xc001101560}, {0xc001568f80, 0x3c}, 0xc00038b4e0?)
        H:/Development/trufflehog/pkg/sources/github/github.go:945 +0x595
github.com/trufflesecurity/trufflehog/v3/pkg/sources/github.(*Source).scan.func1()
        H:/Development/trufflehog/pkg/sources/github/github.go:675 +0x77f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        C:/Users/dsieradski/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        C:/Users/dsieradski/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
```

### Steps to Reproduce

`trufflehog github --org=$env:GITHUB_ORG --include-members --token=$env:GITHUB_TOKEN --trace`

## Environment
 * OS: Windows 
 * Version: 10

## Additional Context
There are a large number of repos being scanned under a single user (me)

**Comment by rgmz** [comment]
It's failing because the logic expects the typical `owner/repo` structure (e.g., `https://github.com/selfagency/vsc-coredx-api.git`). However, this assumption fails for GitHub Gists (e.g., `https://gist.github.com/04638581c1102757cc2c0049463b4c21.git`).

https://github.com/trufflesecurity/trufflehog/blob/b5b01d3eba8fca303e1775f3c7b8b9b0fc275332/pkg/sources/github/github.go#L943-L945
https://github.com/trufflesecurity/trufflehog/blob/b5b01d3eba8fca303e1775f3c7b8b9b0fc275332/pkg/sources/github/github.go#L1087-L1092

This will need to be changed to handle Gists.
