### ISSUE TITLE
--json flag does not output as JSON standard

### ISSUE THREAD

**Issue by CaptainJimmy** [trufflesecurity/trufflehog#169]
when run from commandline, the output to stdio is just aa stream of objects, with no delimination or encapsulation with square brackets.  THe only way i can get this into *ACTUAL* json so i can import the results into something else is by using some VIM-fu and string replacing them in.

**Comment by meyerbro** [comment]
https://stackoverflow.com/questions/34477547/how-to-combine-the-sequence-of-objects-in-jq-into-one-object

Workaround for now ^^^

**Comment by hellasecure** [comment]
Had this issue with returning TruffleHog results to a Flask endpoint as application/json HTTP response type. Since each finding is it's own JSON block per line, json.loads will not accept it. At first I returned it using splitlines as it will take each JSON block per line and place it into a list. But what was returned from it is an array of large String JSON blobs.

So I needed to iterate over each list item with json.loads and this made the entire HTTP response body JSON instead of an array of String JSON blobs.

```
def scan_repo(self):
   process = subprocess.Popen(trufflehog_command, stdout=subprocess.PIPE, shell=True)
   output_json = process.communicate()[0].strip()
   return json.dumps([json.loads(finding) for finding in output_json.decode("utf-8").splitlines()])
```

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

I believe this is no longer an issue in the new version.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this PR.
