### ISSUE TITLE
Add "Authorization" and "Header signature

### ISSUE THREAD

**Issue by numoworld** [trufflesecurity/trufflehog#2093]
## Description
I ran trufflehog against my repository, where I intentionally left a Bearer authorization token that looks like this:
![изображение](https://github.com/trufflesecurity/trufflehog/assets/32400447/f890da9e-f443-4931-96ff-233c476e4406)
But trufflehog found nothing. 

### Preferred Solution
Add Authorization and Bearer signature for secret extraction

**Comment by zricethezav** [comment]
@numoworld you can use a custom regex detector if you want. A bearer token rule without an endpoint to hit would result in unverified findings.

**Comment by cwildman** [comment]
@zricethezav since trufflehog supports running with verification disabled, is there space for a feature where there are detectors that explicitly do not support verification and are only used when verification is disabled? This allows users to choose whether they want to leverage trufflehog for very obvious secrets patterns at the risk of false positives. Users may have other ways to mitigate false positives via entropy filtering or private verification.
