### ISSUE TITLE
Only search back to fork

### ISSUE THREAD

**Issue by minispooner** [trufflesecurity/truffleHog#274]
**Is your feature request related to a problem? Please describe.**
Scanning can take SO much longer if the target repo was a fork from a larger project.

**Describe the solution you'd like**
I want to be able to scope a scan (ie --from-fork) to only scan commit diffs back to the fork. This way, I only scan post-fork committed secrets.

**Describe alternatives you've considered**
I could explicitly add exceptions but it's a very manual and time consuming process.

**Additional context**
NA

**Comment by dxa4481** [comment]
Hi @minispooner 

This feature exists, it's the `since_commit` flag documented in the README

**Comment by minispooner** [comment]
Thanks for the quick response @dxa4481. I saw that flag, but is there a way to look back and find the original commit hash from the original fork? I've tried looking but haven't been able to find the fork's commit hash. Perhaps it's not possible if a repo is rebased to the original etc. I'm no git pro here.

**Comment by dxa4481** [comment]
If both the fork and the original have had additional commits since the fork, you probably need to go through the commit logs and find the divergent commit to start scanning from. Off the top of my head one way to do this is saving `git log` to a file for both the original and the fork, and diffing the two files to see where they split apart
