### ISSUE TITLE
Option to not verify ssl certificates in git option

### ISSUE THREAD

**Issue by MrJico** [trufflesecurity/trufflehog#314]
# Hello trufflehog devs
## Thanks for all the hard work that you have done

I am requesting to add support for an `-k` option to bypass ssl validations.

example project that empelents this feature: [gobuster](https://github.com/OJ/gobuster)

**Comment by bolshoytoster** [comment]
@MrJico looks simple-ish since most modules use `common.SaneHttpClient` we just need to set `http.Client.Transport.TLSClientConfig.InsecureSkipVerify` to true if `-k` is specified:
https://github.com/trufflesecurity/trufflehog/blob/ea95e886ba366541ac08959d4e9d4e49d02c6863/pkg/common/http.go#L124-L129

It probably also needs to be implemented for the other clients there, so it might be easiest to add it to `NewCustomTransport`:
https://github.com/trufflesecurity/trufflehog/blob/ea95e886ba366541ac08959d4e9d4e49d02c6863/pkg/common/http.go#L87-L92

**Comment by bolshoytoster** [comment]
@MrJico I've just implemented this in [my fork](https://github.com/bolshoytoster/trufflehog), could you see if it works properly.

**Comment by MrJico** [comment]
@bolshoytoster  unfortunately I'm not skilled in golang and can't not testit, same for trufflehog
thanks for the hard work ❤

**Comment by bolshoytoster** [comment]
@MrJico I think you can just run `go build` at the top level of the project which will build an executable you can run.

**Comment by MrJico** [comment]
i'm closing this issue because it didn't get any tracking. and no updated on the issue, thanks @bolshoytoster for your work
