### ISSUE TITLE
EmbeddedEndpointSetter test failing

### ISSUE THREAD

**Issue by rgmz** [trufflesecurity/trufflehog#3819]
> @mcastorina This test is failing; not sure why.
>
> Edit: it looks like #3308 changed the logic in a way that subtly broke the test.
>
> ```
> --- FAIL: TestEmbeddedEndpointSetter (0.00s)
>     endpoint_customizer_test.go:12: 
>                 Error Trace:    /tmp/trufflehog/pkg/detectors/endpoint_customizer_test.go:12
>                 Error:          Not equal: 
>                                 expected: []string{"baz"}
>                                 actual  : []string(nil)
>                                 
>                                 Diff:
>                                 --- Expected
>                                 +++ Actual
>                                 @@ -1,4 +1,2 @@
>                                 -([]string) (len=1) {
>                                 - (string) (len=3) "baz"
>                                 -}
>                                 +([]string) <nil>
>                                  
>                 Test:           TestEmbeddedEndpointSetter
> FAIL
> ```
> https://github.com/trufflesecurity/trufflehog/blob/bf6f3136971c9d21c6ef5a6d9bd1d11520102c30/pkg/detectors/endpoint_customizer_test.go#L12

_Originally posted by @rgmz in https://github.com/trufflesecurity/trufflehog/issues/3773#issuecomment-2541588054_

----

Unclear whether the feature is broken or the test is broken.

**Comment by mcastorina** [comment]
> Unclear whether the feature is broken or the test is broken.

It could be either depending on how you view it. I have two thoughts:

* The feature is broken because calling `Endpoints` should never return an empty list
* The test is broken because it wasn't initialized correctly

tbh I'm not too happy with how the endpoint customization feature is implemented. I wonder if it would be better to centralize it in the engine somehow? Open to suggestions!

**Comment by kashifkhan0771** [comment]
We will try to make this better in detectors as config feature 🚀

**Comment by rgmz** [comment]
> tbh I'm not too happy with how the endpoint customization feature is implemented. I wonder if it would be better to centralize it in the engine somehow? Open to suggestions!

What's the use case for `useCloudEndpoint` and `useFoundEndpoints`?

https://github.com/trufflesecurity/trufflehog/blob/dde8f8a06d5463de2f2cce5e7a8afdcdfccf6b7b/pkg/detectors/endpoint_customizer.go#L45-L48

It seems like the expected behaviour is for them to be `true` — and indeed they're hard-coded to `true`in `defaults.go` — but because of how structs/zero values work in Go, it defaults to `false` which can silently break things.
https://github.com/trufflesecurity/trufflehog/blob/dde8f8a06d5463de2f2cce5e7a8afdcdfccf6b7b/pkg/engine/defaults/defaults.go#L1681-L1683

**Comment by mcastorina** [comment]
Yeah, that's a great point. I can't remember why we structured it to be opt-in, so a reason probably doesn't exist.

The overall goal of the feature is to allow detectors to be configured with whichever endpoints to verify against. There are three sources for these endpoints: the cloud hosted endpoint, user-supplied endpoints, and endpoints found by the detector itself. Any combination of these should be allowed (e.g. verify against user-supplied endpoints plus the cloud endpoint).

With how it is currently implemented, a detector follows this pattern to allow the engine to configure which endpoints to use:

```go
type Scanner struct {
    EndpointCustomizer // embed the struct
}

// ...

for _, endpoint := range s.Endpoints(foundEndpoints) {
    // .. verify with endpoint
}
```

I think the biggest footgun with this approach is that `Endpoints()` could return an empty list causing us to silently not verify secrets for that detector (due to iteration over an empty list).

**Comment by mcastorina** [comment]
> You also can't choose which combination to use for a specific detector iteration.

I think at the root of this observation is a question of what a detector is / how it should be used. Are they:

* functional "plugins" to the engine - configured at startup and they detect the same way throughout the scan. You can have as few or as many as you want (even repeated ones).
* "first class" components - configurable at runtime or a per-scan basis (or even mid-scan).
* something else
